name: System Information push
on: push
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Print System Info
        run: |
          date
          hostname
          whoami
          pwd
          echo " Hello DevOps "
          echo " Disk Usage "
          
