name: Practice Workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo " Build is running...... "
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo " Test is running....... "
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo " Deploying application "
