name: test_inputs
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select Environment
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - uat
      artifact_tag:
        description: select git tag to depoy
        required: true
jobs:
  test_input:
    runs-on: ubuntu-latest
    steps:
      - name: deploy the application
        run: " deploying the ${{ inputs.artifact_tag }} app into ${{ inputs.environment }} "
